 sudo  apt install -y php
 sudo  apt install -y curl
 sudo  apt install -y php-xmlrpc
 sudo  apt install -y phpoap
 sudo  apt install -y php-gd
 sudo  apt install -y php-xml
 sudo  apt install -y php-cli
 sudo  apt install -y php-zip
 sudo  apt install -y php-bcmath
 sudo  apt install -y php-tokenizer
 sudo  apt install -y php-json
 sudo  apt install -y php-pgsql
 sudo  apt install -y php-curl
 sudo  apt install -y php-mbstring 
 sudo  apt install -y postgresql
 sudo  apt install -y phppgadmin
 sudo  apt install -y composer
 sudo  apt install -y php-xdebug
 sudo  apt install -y php-mysql
 sudo apt install -y  phpunit
 sudo apt install -y  php-sqlite3
 sudo apt-get install -y php-mongodb
 sudo apt-get  install  -y nginx
 sudo apt install -y php-fpm
 sudo ufw allow 'Nginx Full'